steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "✅ Desplegando start_compute_instance..."
        gcloud functions deploy start_compute_instance \
          --runtime python310 \
          --trigger-topic start-compute \
          --entry-point start_compute_instance \
          --region=GCP_REGION=GCP_REGION:lates \
          --source=start-aclimate-instance \
          --set-secrets=PROJECT_ID=PROJECT_ID:latest,ZONE=ZONE:latest,INSTANCE_NAME=INSTANCE_NAME:latest \
          --no-allow-unauthenticated

        echo "✅ Desplegando stop_compute_instance..."
        gcloud functions deploy stop_compute_instance \
          --runtime python310 \
          --trigger-topic stop-compute \
          --entry-point stop_compute_instance \
          --region=GCP_REGION=GCP_REGION:lates \
          --source=stop-aclimate-instance \
          --set-secrets=PROJECT_ID=PROJECT_ID:latest,ZONE=ZONE:latest,INSTANCE_NAME=INSTANCE_NAME:latest \
          --no-allow-unauthenticated
timeout: 1200s
