steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |

        echo "✅ Creando temas de Pub/Sub..."
        gcloud pubsub topics create start-compute || echo "El tema start-compute ya existe"
        gcloud pubsub topics create stop-compute || echo "El tema stop-compute ya existe"

        echo "✅ Desplegando start_compute_instance..."
        gcloud functions deploy start_compute_instance \
          --runtime python310 \
          --trigger-topic start-compute \
          --entry-point start_compute_instance \
          --region=northamerica-northeast2 \
          --source=./start-aclimate-instance \
          --set-secrets=PROJECT_ID=GCP_PROJECT_ID:latest,ZONE=GCP_ZONE:latest,INSTANCE_NAME=GCP_INSTANCE_NAME:latest \
          --no-allow-unauthenticated

        echo "✅ Desplegando stop_compute_instance..."
        gcloud functions deploy stop_compute_instance \
          --runtime python310 \
          --trigger-topic stop-compute \
          --entry-point stop_compute_instance \
          --region=northamerica-northeast2 \
          --source=./stop-aclimate-instance \
          --set-secrets=PROJECT_ID=GCP_PROJECT_ID:latest,ZONE=GCP_ZONE:latest,INSTANCE_NAME=GCP_INSTANCE_NAME:latest \
          --no-allow-unauthenticated

        echo "✅ Creando Cloud Schedulers..."
        # Scheduler para iniciar la instancia el día 5 de cada mes a las 2 AM
        gcloud scheduler jobs create pubsub start-compute-5 \
          --schedule="0 2 5 * *" \
          --time-zone="America/Bogota" \
          --topic=start-compute \
          --message-body="{}" \
          --location=northamerica-northeast1

        # Scheduler para iniciar la instancia el día 15 de cada mes a las 2 AM
        gcloud scheduler jobs create pubsub start-compute-15 \
          --schedule="0 2 15 * *" \
          --time-zone="America/Bogota" \
          --topic=start-compute \
          --message-body="{}" \
          --location=northamerica-northeast1

        # Scheduler para apagar la instancia el día 7 de cada mes a las 11 PM
        gcloud scheduler jobs create pubsub stop-compute-7 \
          --schedule="0 23 7 * *" \
          --time-zone="America/Bogota" \
          --topic=stop-compute \
          --message-body="{}" \
          --location=northamerica-northeast1

        # Scheduler para apagar la instancia el día 20 de cada mes a las 11 PM
        gcloud scheduler jobs create pubsub stop-compute-20 \
          --schedule="0 23 20 * *" \
          --time-zone="America/Bogota" \
          --topic=stop-compute \
          --message-body="{}" \
          --location=northamerica-northeast1

        # Programar el encendido a las 12:10 AM
        gcloud scheduler jobs create pubsub start-compute-test \
          --schedule="10 12 * * *" \
          --time-zone="America/Bogota" \
          --topic=start-compute \
          --message-body="{}" \
          --location=northamerica-northeast1

        # Programar el apagado a las 12:15 AM
        gcloud scheduler jobs create pubsub stop-compute-test \
          --schedule="15 12 * * *" \
          --time-zone="America/Bogota" \
          --topic=stop-compute \
          --message-body="{}" \
          --location=northamerica-northeast1

timeout: 1200s

options:
  logging: CLOUD_LOGGING_ONLY
